spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dbreactive
    username: postgres
    password: android9
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    user: postgres
    password: android9
    url: jdbc:postgresql://localhost:5432/dbreactive
    server:
      error:
        include-stacktrace=never: